[package]
name = "tauri-test"
version = "0.0.0"
description = "tauri-description"
authors = ["Mr.Li"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
sysinfo = "0.30"

[features]
custom-protocol = ["tauri/custom-protocol"]
